# Generated by Django 3.2.3 on 2022-03-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOAN_CALCULATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('middle_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('loan_amount', models.IntegerField(default=0)),
                ('loan_term', models.IntegerField(default=0)),
            ],
        ),
    ]
